---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: create-jira-from-pr-run
spec:
  pipelineRef:
    name: create-jira-from-pr
  params:
    - name: PR_URL
      value: "{{ repo_url }}/pull/{{ pull_request_number }}"
    - name: GITHUB_TOKEN_SECRET
      value: "{{ git_auth_secret }}"
    - name: GITHUB_TOKEN_KEY
      value: "git-provider-token"
    - name: AI_TOKEN_SECRET
      value: "gemini"
    - name: AI_TOKEN_KEY
      value: "gemini-token"
    - name: JIRA_TOKEN_KEY
      value: "jira-token"
    - name: JIRA_TOKEN_SECRET
      value: "jira"
    - name: JIRA_USER_EMAIL
      value: "cboudjna@redhat.com"
    - name: JIRA_PROJECT
      value: "SRVKP"
    - name: JIRA_TEXT
      value: "{{ trigger_comment }}"
